<robot xmlns:xacro="http://wiki.ros.org/xacro" name="$(arg prefix)mycarwithlidarandcamera">
    <xacro:arg name="prefix" default="" />
    <xacro:arg name="namespace" default="" />

    <xacro:property name="footprint_radius" value="0.003"/>
    <xacro:property name="base_radius" value="0.3"/>
    <xacro:property name="base_length" value="0.24"/>
    <xacro:property name="lidi" value="0.045"/>
    <xacro:property name="base_joint_z" value="${base_length/2 + lidi}"/>
    <xacro:property name="wheel_radius" value="0.0975"/>
    <xacro:property name="wheel_length" value="0.045"/>
    <xacro:property name="PI" value="3.1415927"/>
    <xacro:property name="wheel_joint_Z" value="${-base_length/2 - lidi + wheel_radius}"/>
    <xacro:property name="small_radius" value="0.0225"/>
    <xacro:property name="small_jointz" value="${-base_length/2 - lidi + small_radius}"/>
    <xacro:property name="cam_x" value="0.02" />
    <xacro:property name="cam_y" value="0.05" />
    <xacro:property name="cam_z" value="0.05" />
    <xacro:property name="cam_off_x" value="0.24" />
    <xacro:property name="cam_off_y" value="0" />
    <xacro:property name="cam_off_z" value="0.245" />
    <xacro:property name="support_radius" value="0.01" />
    <xacro:property name="support_length" value="0.3" />
    <xacro:property name="support_off_x" value="0" />
    <xacro:property name="support_off_y" value="0" />
    <xacro:property name="support_off_z" value="0.3" />
    <xacro:property name="livox_off_x" value="0" />
    <xacro:property name="livox_off_y" value="0" />
    <xacro:property name="livox_off_z" value="${support_length/2}" />


    <xacro:macro name="sphere_inertial_matrix" params="m r">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0"
                     iyy="${2*m*r*r/5}" iyz="0"
                     izz="${2*m*r*r/5}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertial_matrix" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
                     iyy="${m*(3*r*r+h*h)/12}" iyz="0"
                     izz="${m*r*r/2}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="Box_inertial_matrix" params="m l w h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(h*h + l*l)/12}" ixy="0" ixz="0"
                     iyy="${m*(w*w + l*l)/12}" iyz="0"
                     izz="${m*(w*w + h*h)/12}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="null_inertial">
        <inertial>
            <mass value="0.1"/>
        <inertia ixx="0.01" ixy="0" ixz="0"
                 iyy="0.01" iyz="0"
                 izz="0.01"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="wheel_func" params="wheel_name flag">
        <link name="$(arg prefix)${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
                <material name="wheel_color">
                    <color rgba="0 0 1.0 0.5 0.3" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
            </collision>
            <xacro:cylinder_inertial_matrix m="9" r="${wheel_radius}" h="${wheel_length}" />
        </link>
        <joint name="$(arg prefix)base_link2_${wheel_name}" type="continuous">
            <parent link="$(arg prefix)base_link" />
            <child link="$(arg prefix)${wheel_name}_wheel"/>
            <origin xyz="0 ${0.3 * flag} ${wheel_joint_Z}" />
            <axis xyz="0 1 0" />
        </joint>
        <gazebo reference="$(arg prefix)${wheel_name}_wheel">
            <material>Gazebo/Red</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="small_wheel_func" params="small_wheel_name flag">
        <link name="$(arg prefix)${small_wheel_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${small_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="black">
                    <color rgba="0.0 0.0 0.0 0.6" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${small_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:sphere_inertial_matrix m="0.72" r="${small_radius}" />
        </link>
        <joint name="$(arg prefix)${small_wheel_name}2base_link" type="continuous">
            <parent link="$(arg prefix)base_link" />
            <child link="$(arg prefix)${small_wheel_name}_wheel" />
            <origin xyz="${0.2775 * flag} 0 ${small_jointz}" />
            <axis xyz="1 1 1" />
        </joint>
        <gazebo reference="$(arg prefix)${small_wheel_name}_wheel">
            <material>Gazebo/Red</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="joint_trans" params="joint_name">
        <transmission name="$(arg prefix)${joint_name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="$(arg prefix)${joint_name}">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="$(arg prefix)${joint_name}_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>
    
    <xacro:macro name="Livox_Mid_gazebo_sensor" params="visualize:=True update_rate:=10 resolution:=0.002 noise_mean:=0.0 noise_stddev:=0.01 name:=livox ros_topic:=/scan samples:=24000 downsample:=1 laser_min_range:=0.1 laser_max_range:=200.0">
      <gazebo reference="$(arg prefix)${name}">
        <sensor type="ray" name="laser_$(arg prefix)${name}">
          <pose>0 0 0 0 0 0</pose>
          <visualize>${visualize}</visualize>
          <update_rate>${update_rate}</update_rate>
          <plugin name="$(arg prefix)gazebo_ros_laser_controller" filename="liblivox_laser_simulation.so">
            <ray>
              <scan>
                <horizontal>
                  <samples>100</samples>
                  <resolution>1</resolution>
                  <min_angle>${0}</min_angle>
                  <max_angle>${2*PI}</max_angle>
                </horizontal>
                <vertical>
                  <samples>360</samples>
                  <resolution>1</resolution>
                  <min_angle>${-7.22/180*PI}</min_angle>
                  <max_angle>${55.22/180*PI}</max_angle>
                </vertical>
              </scan>
              <range>
                <min>${laser_min_range}</min>
                <max>${laser_max_range}</max>
                <resolution>${resolution}</resolution>
              </range>
              <noise>
                <type>gaussian</type>
                <mean>${noise_mean}</mean>
                <stddev>${noise_stddev}</stddev>
              </noise>
            </ray>
            <visualize>${visualize}</visualize>
            <samples>${samples}</samples>
            <downsample>${downsample}</downsample>
            <csv_file_name>package://livox_laser_simulation/scan_mode/mid360.csv</csv_file_name>
            <ros_topic>$(arg namespace)${ros_topic}</ros_topic>
          </plugin>
        </sensor>
      </gazebo>
    </xacro:macro>

    <xacro:macro name="Livox_Mid40" params="visualize:=True name:=livox">
        <link name="$(arg prefix)${name}_base">
            <xacro:null_inertial/>
            <visual>  
                <origin xyz="0.00 0 0.0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://livox_laser_simulation/meshes/livox_mid40.dae" scale="0.001 0.001 0.001">
                    </mesh>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" /> 
                <geometry> 
                    <mesh filename="package://livox_laser_simulation/meshes/livox_mid40.dae" scale="0.001 0.001 0.001"> 
                    </mesh> 
                </geometry>
            </collision>
        </link>
        <link name="$(arg prefix)${name}">
            <xacro:null_inertial/>
        </link>

        <joint name="$(arg prefix)${name}_to_${name}_base_joint" type="fixed">
            <parent link="$(arg prefix)${name}_base"/>
            <child link="$(arg prefix)${name}"/>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        </joint>
        <xacro:Livox_Mid_gazebo_sensor name="${name}" visualize="${visualize}" ros_topic="/livox_scan"/>
    </xacro:macro>


    <link name="$(arg prefix)base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}" />
            </geometry>
        </visual>
    </link>

    <link name="$(arg prefix)base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue">
                <color rgba="0 0 1.0 0.5" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="18" r="${base_radius}" h="${base_length}" />
    </link>
    <gazebo reference="$(arg prefix)base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <joint name="$(arg prefix)base_link2base_footprint" type="fixed">
        <parent link="$(arg prefix)base_footprint" />
        <child link="$(arg prefix)base_link"/>
        <origin xyz="0 0 ${base_joint_z}" />
    </joint>

    <xacro:wheel_func wheel_name="left" flag="1" />
    <xacro:wheel_func wheel_name="right" flag="-1" />
    <xacro:small_wheel_func small_wheel_name="front" flag="1" />
    <xacro:small_wheel_func small_wheel_name="back" flag="-1" />

    <link name="$(arg prefix)support">
        <visual>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="red">
                <color rgba="0.8 0.2 0.0 0.8" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="0.1" r="${support_radius}" h="${support_length}" />
    </link>
    <gazebo reference="$(arg prefix)support">
        <material>Gazebo/Grey</material>
    </gazebo>
    <joint name="$(arg prefix)support2base_link" type="fixed">
        <parent link="$(arg prefix)base_link" />
        <child link="$(arg prefix)support" />
        <origin xyz="${support_off_x} ${support_off_y} ${support_off_z}" />
    </joint>

    <link name="$(arg prefix)support_depth" />
    <joint name="$(arg prefix)support2support_depth" type="fixed">
        <parent link="$(arg prefix)support" />
        <child link="$(arg prefix)support_depth" />
        <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}" />
    </joint>

    <xacro:Livox_Mid40 name="livox" />
    
    <joint name="$(arg prefix)livox_joint" type="fixed">
        <parent link="$(arg prefix)support" />
        <child link="$(arg prefix)livox_base" />
        <origin xyz="${livox_off_x} ${livox_off_y} ${livox_off_z}" rpy="0 0 0" />
    </joint>


    <xacro:joint_trans joint_name="base_link2_left" />
    <xacro:joint_trans joint_name="base_link2_right" />
    <gazebo>
        <plugin name="$(arg prefix)differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>true</publishWheelTF>
            <robotNamespace>$(arg namespace)</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <legacyMode>true</legacyMode>
            <leftJoint>$(arg prefix)base_link2_left</leftJoint>
            <rightJoint>$(arg prefix)base_link2_right</rightJoint>
            <wheelSeparation>${base_radius * 2}</wheelSeparation>
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <commandTopic>$(arg namespace)/cmd_vel</commandTopic>
            <odometryFrame>$(arg prefix)odom</odometryFrame>
            <odometryTopic>$(arg namespace)/odom</odometryTopic>
            <robotBaseFrame>$(arg prefix)base_footprint</robotBaseFrame>
        </plugin>
    </gazebo>

    <gazebo reference="$(arg prefix)support">
        <sensor type="depth" name="$(arg prefix)kinect_camera">
            <always_on>true</always_on>
            <update_rate>20.0</update_rate>
            <camera>
                <horizontal_fov>${60.0*PI/180.0}</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>5</far>
                </clip>
            </camera>
            <plugin name="$(arg prefix)kinect_camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <cameraName>$(arg namespace)/camera</cameraName>
                <alwaysOn>true</alwaysOn>
                <updateRate>10</updateRate>
                <imageTopicName>$(arg namespace)/rgb/image_raw</imageTopicName>
                <depthImageTopicName>$(arg namespace)/depth/image_raw</depthImageTopicName>
                <pointCloudTopicName>$(arg namespace)/depth/points</pointCloudTopicName>
                <cameraInfoTopicName>$(arg namespace)/rgb/camera_info</cameraInfoTopicName>
                <depthImageCameraInfoTopicName>$(arg namespace)/depth/camera_info</depthImageCameraInfoTopicName>
                <frameName>$(arg prefix)support_depth</frameName>
                <baseline>0.1</baseline>
                <distortion_k1>0.0</distortion_k1>
                <distortion_k2>0.0</distortion_k2>
                <distortion_k3>0.0</distortion_k3>
                <distortion_t1>0.0</distortion_t1>
                <distortion_t2>0.0</distortion_t2>
                <pointCloudCutoff>0.2</pointCloudCutoff>
            </plugin>
        </sensor>
    </gazebo>
</robot>